# Generated by Django 3.2.13 on 2022-06-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
